name = "buyppy-auth-ms"
compatibility_date = "2024-07-17"

[vars]
DATABASE_URL = "postgresql://buyppy_ps_user:19kfH8gEOuhN0cYyhZ4ZyoFfFDNEoVc4@dpg-cqbhsdqju9rs7391lflg-a.oregon-postgres.render.com/buyppy_ps"
DIRECT_DATABASE_URL = "postgresql://buyppy_ps_user:19kfH8gEOuhN0cYyhZ4ZyoFfFDNEoVc4@dpg-cqbhsdqju9rs7391lflg-a.oregon-postgres.render.com/buyppy_ps"
JWT_SECRET = "123#321"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
