name = "materials-ms"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[env.dev]
name = "buyppy-material-ms-dev"

[env.stg]
name = "buyppy-material-ms-stg"

[env.prod]
name = "buyppy-material-ms-prod"

[vars]
DATABASE_URL = ""
DIRECT_URL = ""
JWT_SECRET = "123#321"

[env.dev.vars]
DATABASE_URL = ""
DIRECT_URL = ""
JWT_SECRET = "123#321"

[env.prod.vars]
DATABASE_URL = ""
DIRECT_URL = ""
JWT_SECRET = "123#321"

[env.stg.vars]
DATABASE_URL = ""
DIRECT_URL = ""
JWT_SECRET = "123#321"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
