name = "buyppy-admin-ms-dev"
compatibility_date = "2024-07-12"

[env.dev]
name = "buyppy-admin-ms-dev"

[env.stg]
name = "buyppy-admin-ms-stg"

[env.prod]
name = "buyppy-admin-ms-prod"

[vars]
DATABASE_URL = "postgresql://buyppy-db_owner:aiykWGY4Df3b@ep-withered-term-a53vlnyx.us-east-2.aws.neon.tech/buyppy-db?sslmode=require"
DIRECT_URL = "postgresql://buyppy_db_user:NvFygzwAtfbUcrMqfw9voWaKTM2YENuh@dpg-cr4d1kogph6c73a79ttg-a.ohio-postgres.render.com/buyppy_db"
JWT_SECRET = "123#321"

[env.dev.vars]
DATABASE_URL = "postgresql://buyppy-db_owner:aiykWGY4Df3b@ep-withered-term-a53vlnyx.us-east-2.aws.neon.tech/buyppy-db?sslmode=require"
DIRECT_URL = "postgresql://buyppy_db_user:NvFygzwAtfbUcrMqfw9voWaKTM2YENuh@dpg-cr4d1kogph6c73a79ttg-a.ohio-postgres.render.com/buyppy_db"
JWT_SECRET = "123#321"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
